namespace: goldyfruit
name: ibmcloud_automation
version: 1.0.1
readme: README.md
authors:
  - Gaëtan Trellu <gaetan.trellu@gmail.com>
  - James Regis <james.regis@gmail.com>

description: Modules to interact with features running on IBM Cloud platform.

license_file: 'LICENSE'

tags:
  - ibmcloud
  - cloud
  - collection
  - vpc
  - vsi
  - classic
  - infrastructure
  - baremetal
  - softlayer

dependencies:
  community.general: "*"

repository: https://github.com/goldyfruit/ibmcloud-ansible-collection
documentation:
homepage: https://github.com/goldyfruit/ibmcloud-ansible-collection
issues: https://github.com/goldyfruit/ibmcloud-ansible-collection/issues

build_ignore:
  - venv
  - ansible_collections
  - tests/output
  - .pytest_cache
  - .vscode
